### ISSUE TITLE
Create player shots column

### ISSUE THREAD

**Issue by MokeEire** [mdewey131/Snappa-Scoreboard#10]
This will be used for points per shot in `game_stats`

**Comment by mdewey131** [comment]
4d9fd2966734852b670d5dd5d4611bb3f1a77017 Adds a points_per_shot column, which I added earlier into the DB. However, it currently does not discount paddling or points scored for the other team so it is more of a measure of overall point production per shot that the player takes than a measure of point production on shots.

**Comment by mdewey131** [comment]
I'm realizing now that we're just going a  column of shots. This can be obtained by removing the existing sums that define points_per_shot and just keeping the ceiling and floor functions. The column "shots" has also now been added to the game_stats table on the database so that it can be appended directly
